#===============COMPULSORY PROGRAM ARGUMENTS=====#
mongo-server:
auth-enable:
#===============COMPULSORY PROGRAM ARGUMENTS=====#

server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${mongo-server}

gwas-curation:
  db: gwas-deposition-local
  auth:
    enabled: ${auth-enable}
    curators:
      auth-mechanism: EMAIL_WHITELISTING

quartz:
  scheduler:
    dbName: gwas-deposition-dev

gwas-deposition-service:
  url: http://193.62.54.159/backend-sajo-testing
  fileupload:
    endpoints:
      submission: /v1/submissions/
  javers:
    url: http://193.62.54.159/backend-sajo-testing
    endpoints:
      javers-submission: /v1/javers/
