server:
  port: 8080
  servlet:
    context-path: /gwas/depo-curation/api


logging:
  level:
    org:
      springframework: ERROR

spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: rabbitmq.rabbitmq.svc.cluster.local
    port: 5672
    username: ebigwasuser
  data:
    mongodb:
      #uri: mongo-0.mongo.gwas-dev.svc.cluster.local,mongo-1.mongo.gwas-dev.svc.cluster.local,mongo-2.mongo.gwas-dev.svc.cluster.local:27017
      uri: mongodb-hhvm-062.ebi.ac.uk:27017,mongodb-hxvm-063.ebi.ac.uk:27017/admin?replicaSet=gwasdepodevrs039
    solr:
      host: http://solr-svc.gwas-dev.svc.cluster.local:8983/solr/


  mail:
    host: outgoing.ebi.ac.uk
    port: 587
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: false
          sendpartial: true
          starttls:
            enable: true

quartz:
  scheduler:
    #dbName: deposition-backend-sandbox
    dbName: gwasdepo
    active: true
  jobs:
    weekly-publication-stats:
      schedule: 0 */10 * 98 * *
    weekly-curationstatus-stats:
      schedule: 0 */30 * 98 * *
    weekly-curationqueue-stats:
      schedule: 0 */30 * 98 * *

gwas-curation:
  auth:
    enabled: true
    curators:
      auth-mechanism: JWT_DOMAIN
  #db: deposition-backend-sandbox
  db: gwasdepo
  proxy-prefix:
  solr:
    enabled: true

email:
  enabled: true


#gwas-deposition-service:
 # fileupload:
    #endpoint : http://gwas-deposition-backend:8080/v1/submissions/
    #url: http://gwas-deposition-backend:8080
    #endpoints:
    #  submission: /v1/submissions/

gwas-deposition-service:
  url: http://gwas-deposition-backend-dev:8080
  fileupload:
    endpoints:
      submission: /gwas/deposition/api/v1/submissions/


gwas-curation-service:
  url: http://localhost:8080
  javers:
    endpoints:
      javers-submission: /gwas/depo-curation/api/v1/javers

gwas-ingest-service:
  url: http://gwas-ingest-service-dev:8080/gwas/ingest/api
  endpoints:
    submission-envelope: /v1/submission-envelopes

goci:
  url: http://snoopy.ebi.ac.uk:9680/gwas/curation
  diseaseTraits:
    endpoints:
      reported-traits-upload: /api/v1/disease-traits/uploads
      reported-traits: /api/v1/disease-traits
      search-reported-traits: /api/v1/disease-traits/search


audit:
  service:
    url: http://gwas-audit-service-dev:8080
  endpoints:
    pub-audit-entries: /publication-audit-entries
    publication: /v1/publications

rabbitmq:
  queue-name: study_change_sandbox
  exchange-name: study_change_exchange_sandbox
  routing-key: study-ingest_sandbox
  sumstats:
    queue-name: metadata-yml-update-sandbox
    exchange-name: metadata-yml-update-exchange-sandbox
    routing-key: metadata-yml-update-route-sandbox
  publication:
    queue-name: publication-sandbox
    exchange-name: publication-exchange-sandbox
    routing-key: publication-route-sandbox