spring:
  data:
    mongodb:
      uri: snoopy.ebi.ac.uk:27017

quartz:
  scheduler:
    dbName: gwas-deposition-test

gwas-curation:
  db: gwas-deposition-test
  auth:
    curators:
      auth-mechanism: EMAIL_WHITELISTING

gwas-deposition-service:
  url: http://193.62.54.159/backend-sajo-testing
  fileupload:
    endpoints:
      submission: /v1/submissions/


gwas-curation-service:
  url: http://localhost:8080
  javers:
    endpoints:
      javers-submission: /v1/javers