#===============COMPULSORY PROGRAM ARGUMENTS=====#
mongo-server:
auth-enable:
#===============COMPULSORY PROGRAM ARGUMENTS=====#

server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${mongo-server}

gwas-curation:
  db: gwas-deposition-local
  auth:
    enabled: ${auth-enable}
    curators:
      auth-mechanism: EMAIL_WHITELISTING

quartz:
  scheduler:
    dbName: gwas-deposition-dev

gwas-deposition-service:
  fileupload:
    endpoint : http://193.62.54.159/backend/v1/submissions/