#===============COMPULSORY PROGRAM ARGUMENTS=====#
mongo-server:
auth-enable:
solr-server:
#===============COMPULSORY PROGRAM ARGUMENTS=====#

server:
  port: 8081
  servlet:
    context-path: /gwas/depo-curation/api

logging:
  level:
    org:
      springframework: DEBUG

spring:
  rabbitmq:
    host: localhost
    port: 5672
  data:
    mongodb:
      uri: ${mongo-server}
    solr:
      host: ${solr-server}


gwas-curation:
  #db: deposition-backend-sandbox
  db: gwasdepo
  auth:
    enabled: ${auth-enable}
    curators:
      auth-mechanism: EMAIL_WHITELISTING
  solr:
    enabled: true

quartz:
  scheduler:
    dbName: gwasdepo

gwas-deposition-service:
  #url: http://hh-rke-wp-webadmin-09-worker-2.caas.ebi.ac.uk:30183/gwas/deposition/api
  url: http://localhost:8082
  fileupload:
    endpoints:
      submission: /v1/submissions/


gwas-curation-service:
  url: http://localhost:8080
  javers:
    endpoints:
      javers-submission: /v1/javers

gwas-ingest-service:
  url: http://localhost:8082/gwas/ingest/api
  endpoints:
    submission-envelope: /v1/submission-envelopes

goci:
  url: http://localhost:8080
  diseaseTraits:
    endpoints:
      reported-traits-upload: /api/v1/disease-traits/uploads
      reported-traits: /api/v1/disease-traits
      search-reported-traits: /api/v1/disease-traits/search


rabbitmq:
  queue-name: study_change_sandbox
  exchange-name: study_change_exchange_sandbox
  routing-key: study-ingest_sandbox
  sumstats:
    queue-name: metadata-yml-update-sandbox
    exchange-name: metadata-yml-update-exchange-sandbox
    routing-key: metadata-yml-update-route-sandbox



