server:
  name: deposition-curation
  port: 80

logging:
  level:
    org:
      springframework: ERROR

quartz:
  scheduler:
    active: false
    instanceName: curationSchedulerJobSchedulerCluster
    environment-config: quartz/environment-config.yaml
    mongodb-pool-size: 10
  jobs:
    weekly-publication-stats:
      schedule: 0 10 14 98 * 6
    weekly-curationstatus-stats:
      schedule: 0 10 21 98 * 1
    weekly-curationqueue-stats:
      schedule: 0 20 21 98 * 1

gwas-curation:
  auth:
    enabled: false
    cert: aap.der
    auto-curator-service-account: auto-curator-service@ebi.ac.uk
    curators:
      auth-mechanism: JWT_DOMAIN
      jwt-domains: self.GWAS_Curator
  solr:
    enabled: true
  email-config:
    #to-address: gwas-curator@ebi.ac.uk,gwas-dev-logs@ebi.ac.uk
    to-address: sajo@ebi.ac.uk
    base-url: https://www.ebi.ac.uk/gwas/deposition/submission/
    docs-url: https://www.ebi.ac.uk/gwas/docs/submission#link-15
    emails:
      publicationweeklystats:
        subject: Weekly Publication stats for %WEEK%
        success: emails/weekly_publication_success.email
      curationsnapshotstats:
        subject: Weekly Curation Snapshot stats for %WEEK%
        success: emails/weekly_curationsnapshotstats_success.email
      curationqueue:
        subject: Weekly Curation Queue for %WEEK%
        success: emails/weekly_curationqueue_success.email
    errors:
      active: false
      receiver: gwas-dev-logs@ebi.ac.uk
      subject: GWAS Deposition App - Error encountered
      email: emails/errors.email

email:
  enabled: false
  config:
    from-address: no-reply@ebi.ac.uk
    from-name: GWAS Curation
    retries: 3

spring:
  profiles:
    active: local

comms:
  messaging:
    enabled: false


europepmc:
  root: https://www.ebi.ac.uk/europepmc/webservices/rest/
  search:
    pubmed: search?query=ext_id:{idlist} src:med&resulttype=core&format=JSON


ftp:
  link:
  user:
  pass:
  app_folder: /curation_app_literature_upload_dev
  weekly_stats_folder: /curation_weekly_stats_dev


curation:
  weekly:
    reports:
      path: /var/log/gwas/WeeklyPublicationStats.tsv

springdoc:
  swagger-ui:
    url: /curation-doc.yaml
    layout: BaseLayout
    disable-swagger-default-url: true
    path: /documentation
  api-docs:
    path: /curation-doc
