#===============COMPULSORY PROGRAM ARGUMENTS=====#
mongo-server:
auth-enable:
solr-server:
#===============COMPULSORY PROGRAM ARGUMENTS=====#

server:
  port: 8081
  servlet:
    context-path: /gwas/depo-curation/api

logging:
  level:
    org:
      springframework: ERROR

spring:
  rabbitmq:
    host: localhost
    port: 5672
  data:
    mongodb:
      uri: mongodb-hhvm-062.ebi.ac.uk:27017,mongodb-hxvm-063.ebi.ac.uk:27017/admin?replicaSet=gwasdepodevrs039
    solr:
      host: ${solr-server}
  mail:
    host: hh-smtp.ebi.ac.uk
    port: 25
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: false
          sendpartial: true
          starttls:
            enable: true

gwas-curation:
  #db: deposition-backend-sandbox
  db: gwasdepo
  auth:
    enabled: ${auth-enable}
    curators:
      auth-mechanism: JWT_DOMAIN
  solr:
    enabled: true

quartz:
  scheduler:
    active: true
    dbName: gwasdepo
    isClustered: false
  jobs:
    weekly-publication-stats:
      schedule: 0 34 13 98 * *
    weekly-curationstatus-stats:
      schedule: 0 15 22 98 * *
    weekly-curationqueue-stats:
      schedule: 0 15 22 98 * *

gwas-deposition-service:
  #url: http://hh-rke-wp-webadmin-09-worker-2.caas.ebi.ac.uk:30183/gwas/deposition/api
  url: http://localhost:8082
  fileupload:
    endpoints:
      submission: /v1/submissions/


gwas-curation-service:
  url: http://localhost:8081/gwas/depo-curation/api
  javers:
    endpoints:
      javers-submission: /v1/javers

audit:
  service:
    url: http://localhost:8085
  endpoints:
    pub-audit-entries: /publication-audit-entries
    publication: /v1/publications

email:
  enabled: true


gwas-ingest-service:
  url: http://localhost:8082/gwas/ingest/api
  endpoints:
    submission-envelope: /v1/submission-envelopes

goci:
  url: http://localhost:8081
  diseaseTraits:
    endpoints:
      reported-traits-upload: /api/v1/disease-traits/uploads
      reported-traits: /api/v1/disease-traits
      search-reported-traits: /api/v1/disease-traits/search

curation:
  weekly:
    reports:
      path: classpath:WeeklyPublicationStats.tsv

rabbitmq:
  queue-name: study_change_sandbox
  exchange-name: study_change_exchange_sandbox
  routing-key: study-ingest_sandbox
  sumstats:
    queue-name: metadata-yml-update-sandbox
    exchange-name: metadata-yml-update-exchange-sandbox
    routing-key: metadata-yml-update-route-sandbox
  publication:
    queue-name: publication-sandbox
    exchange-name: publication-exchange-sandbox
    routing-key: publication-route-sandbox
