#===============COMPULSORY PROGRAM ARGUMENTS=====#
mongo-server:
auth-enable:
#===============COMPULSORY PROGRAM ARGUMENTS=====#

server:
  port: 8081

spring:
  data:
    mongodb:
      uri: ${mongo-server}

gwas-curation:
  db: deposition-backend-sandbox
  auth:
    enabled: ${auth-enable}
    curators:
      auth-mechanism: EMAIL_WHITELISTING

quartz:
  scheduler:
    dbName: gwas-deposition-dev

gwas-deposition-service:
  url: http://hh-rke-wp-webadmin-09-worker-2.caas.ebi.ac.uk:30183/gwas/deposition/api
  fileupload:
    endpoints:
      submission: /v1/submissions/


gwas-curation-service:
  url: http://localhost:8080
  javers:
    endpoints:
      javers-submission: /v1/javers

goci:
  url: http://localhost:8080
  diseaseTraits:
    endpoints:
      reported-traits-upload: /api/v1/disease-traits/uploads
      reported-traits: /api/v1/disease-traits
      search-reported-traits: /api/v1/disease-traits/search